# Use root/example as user/password credentials
version: '3'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
      POSTGRES_USER: demo
    ports:
      - 5432:5432

  api-demo:
    image: quarkus-api-demo:latest
    build: .
    depends_on:
      - db
      - keycloak
    links:
      - "keycloak:keycloak"
      - "db:db"
    environment:
      QUARKUS_PROFILE: dev
    ports:
      - 9080:9080
      - 5005:5005

  keycloak:
    image: dannybastos/keycloak:18.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    ports:
      - 8080:8080
    restart: unless-stopped